### ISSUE TITLE
Accessible on iOS devices

### ISSUE THREAD

**Issue by cprichard** [rtivital/omatsuri#10]
I've tried to open https://omatsuri.app/, https://omatsuri.app/html-symbols, etc. on iOS (v13) browsers (e.g. Safari, Firefox, Microsoft Edge, iCab) but the page displays nothing. I tried saving the link to my Home Screen. The link opens to a blank screen.

Thank you,

**Comment by rtivital** [comment]
Hi Craig, I'm not able to reproduce this issue on my iPhone or iPad, can you try reseting the cache?
