### ISSUE TITLE
white screen on safari

### ISSUE THREAD

**Issue by matthewtrask** [rtivital/omatsuri#13]
I tried opening the site on safari (macOS Catalina v 10.15.4 | Safari v 13.1) and it was just a blank white page. When I refreshed, I would see a flicker of the page, but then the white screen again. 

When I open it on Firefox it works perfectly fine. There seems to be a few errors in the console on Safari but not sure if any of them are related to page load or not. 

The first screenshot here is firefox, the second is safari, the third is the console in firefox. Since this is the first time I've visited the app I wouldn't imagine something like caching would cause the issue but I emptied the safari cache just to be sure. 

![Screen Shot 2021-02-16 at 9 41 07 AM (2)](https://user-images.githubusercontent.com/4731244/108085604-1f926000-703b-11eb-8782-e0b68d20ab7e.png)
![Screen Shot 2021-02-16 at 9 40 58 AM (2)](https://user-images.githubusercontent.com/4731244/108085606-202af680-703b-11eb-9458-a99610e516d5.png)
![Screen Shot 2021-02-16 at 9 40 27 AM](https://user-images.githubusercontent.com/4731244/108085496-02f62800-703b-11eb-8fe1-54a475cc684c.png)

**Comment by rtivital** [comment]
Hi Matt, unfortunately I cannot reproduce this, it works fine in Safari for me (macos 11.2). It would be great help if you investigate or fix the issue  in dev mode (that should provide more meaningful error messages). You can follow a simple instruction on getting started in CONTRIBUTING.md file – https://github.com/rtivital/omatsuri/blob/master/CONTRIBUTING.md 

If you decide to contribute and fix the issue, please add  yourself to contributors (if you want to appear on this list of course).

**Comment by rtivital** [comment]
I was able to debug this myself, the problem was that older versions of Safari  do not support `window.matchMedia().addEventListener` and work only with  deprecated `window.matchMedia().addListener`. You can see the solution [here](https://github.com/rtivital/xooks/blob/master/src/use-color-scheme/use-color-scheme.ts#L3-L11)
