### ISSUE TITLE
White screens of death

### ISSUE THREAD

**Issue by fuzzfree** [rtivital/omatsuri#16]
Hi! I checked a couple of pages with FF and they are blank. Various  console errors appear.

![Capture](https://user-images.githubusercontent.com/12214846/119228856-a57fe480-bb1d-11eb-8683-98c01f591fda.PNG)

**Comment by rtivital** [comment]
Hi, this is usually happens in old versions of FF without service workers support or they are turned off in browser settings (works fine in default configuration and modern versions)

**Comment by fuzzfree** [comment]
Hi, I have the latest versions. It does not work in private browsing mode, it works ok in normal mode. A friendly message would be the best in such case, handling the error gracefully and notify the user. Thanks!

**Comment by rtivital** [comment]
I've released a fix, now it works in private mode in FF
