### ISSUE TITLE
Keyboard events not updated correctly with AZERTY keyboard

### ISSUE THREAD

**Issue by maxime-louf** [rtivital/omatsuri#17]
Hello, using the "Keyboard events code" app, event.code doesn't return the correct response with an AZERTY keyboard.
For example, pressing letter 'A' return event.code 'keyQ' instead of 'keyA'. Same when pressing 'Z' and so on. 
However event.key return the correct key.
Thank you

**Comment by rtivital** [comment]
That's how browser handles keyboard events, there is not much we can do on our side
https://github.com/rtivital/omatsuri/blob/master/src/apps/events-keycode/generate-event-data.js

**Comment by maxime-louf** [comment]
Oh you're right. So i feel like event.code shouldn't be used  since it's response can't be properly anticipated and event.key should be preferred.

**Comment by rtivital** [comment]
event.key cannot be used, it represents a pressed character, not key, for example, you will get `E` value for English keyboard and `У` (Russian letter) for Russian

**Comment by maxime-louf** [comment]
Fair enough, closing this issue.
